In [1]:
#panda do not enforce unique indexes. It is data analyst call
employee = {
    'id':[1, 2, 3],
    'name':['Nitin', 'Gautam', 'Ramesh'],
    'email':['a@x.com', 'b@x.com', 'c@x.com']   
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(employee)

In [5]:
df['email']

0    a@x.com
1    b@x.com
2    c@x.com
Name: email, dtype: object

In [7]:
#set email as index.
df.set_index('email')

         id    name
email
a@x.com   1   Nitin
b@x.com   2  Gautam
c@x.com   3  Ramesh

In [8]:
#After above execution Panda does not change the indexes. The default one is still some number
df

   id    name    email
0   1   Nitin  a@x.com
1   2  Gautam  b@x.com
2   3  Ramesh  c@x.com

In [10]:
#To change the indexes permanently we need to set them true.
df.set_index('email', inplace=True)

In [11]:
df

         id    name
email
a@x.com   1   Nitin
b@x.com   2  Gautam
c@x.com   3  Ramesh

In [12]:
df.index

Index(['a@x.com', 'b@x.com', 'c@x.com'], dtype='object', name='email')

In [13]:
df.loc['b@x.com']

id           2
name    Gautam
Name: b@x.com, dtype: object

In [14]:
df.loc['b@x.com', 'name']

'Gautam'

In [15]:
df.iloc[0]

id          1
name    Nitin
Name: a@x.com, dtype: object

In [17]:
df.reset_index(inplace=True)

In [18]:
df

     email  id    name
0  a@x.com   1   Nitin
1  b@x.com   2  Gautam
2  c@x.com   3  Ramesh

In [19]:
import pandas as pd

In [21]:
df = pd.read_csv('stack-overflow-data/survey_results_public.csv')

In [22]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [24]:
#setting indexes during reading of csv file
df = pd.read_csv('stack-overflow-data/survey_results_public.csv', index_col='Respondent' )

In [25]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [26]:
df.loc[1]

MainBranch                 I am a student who is learning to code
Hobbyist                                                      Yes
OpenSourcer                                                 Never
OpenSource      The quality of OSS and closed source software ...
Employment                 Not employed, and not looking for work
                                      ...
Sexuality                                 Straight / Heterosexual
Ethnicity                                                     NaN
Dependents                                                     No
SurveyLength                                Appropriate in length
SurveyEase                             Neither easy nor difficult
Name: 1, Length: 84, dtype: object

In [27]:
df = pd.read_csv('stack-overflow-data/survey_results_schema.csv', index_col='Column' )

In [29]:
df

                                                   QuestionText
Column
Respondent    Randomized respondent ID number (not in order ...
MainBranch    Which of the following options best describes ...
Hobbyist                                Do you code as a hobby?
OpenSourcer         How often do you contribute to open source?
OpenSource    How do you feel about the quality of open sour...
...                                                         ...
Sexuality     Which of the following do you currently identi...
Ethnicity     Which of the following do you identify as? Ple...
Dependents    Do you have any dependents (e.g., children, el...
SurveyLength  How do you feel about the length of the survey...
SurveyEase    How easy or difficult was this survey to compl...

[85 rows x 1 columns]

In [31]:
df.loc['SurveyEase']

QuestionText    How easy or difficult was this survey to compl...
Name: SurveyEase, dtype: object

In [32]:
df.loc['SurveyEase', 'QuestionText']

'How easy or difficult was this survey to complete?'

In [33]:
df.sort_index()

                                                    QuestionText
Column
Age            What is your age (in years)? If you prefer not...
Age1stCode     At what age did you write your first line of c...
BetterLife     Do you think people born today will have a bet...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BlockchainOrg  How is your organization thinking about or imp...
...                                                          ...
WorkPlan                 How structured or planned is your work?
WorkRemote                       How often do you work remotely?
WorkWeekHrs     On average, how many hours per week do you work?
YearsCode      Including any education, how many years have y...
YearsCodePro   How many years have you coded professionally (...

[85 rows x 1 columns]

In [34]:
df.sort_index(ascending=False)

                                                    QuestionText
Column
YearsCodePro   How many years have you coded professionally (...
YearsCode      Including any education, how many years have y...
WorkWeekHrs     On average, how many hours per week do you work?
WorkRemote                       How often do you work remotely?
WorkPlan                 How structured or planned is your work?
...                                                          ...
BlockchainOrg  How is your organization thinking about or imp...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BetterLife     Do you think people born today will have a bet...
Age1stCode     At what age did you write your first line of c...
Age            What is your age (in years)? If you prefer not...

[85 rows x 1 columns]

In [35]:
df.sort_index(ascending=True, inplace=True)

In [36]:
df

                                                    QuestionText
Column
Age            What is your age (in years)? If you prefer not...
Age1stCode     At what age did you write your first line of c...
BetterLife     Do you think people born today will have a bet...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BlockchainOrg  How is your organization thinking about or imp...
...                                                          ...
WorkPlan                 How structured or planned is your work?
WorkRemote                       How often do you work remotely?
WorkWeekHrs     On average, how many hours per week do you work?
YearsCode      Including any education, how many years have y...
YearsCodePro   How many years have you coded professionally (...

[85 rows x 1 columns]